# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'command_info.ui',
# licensing of 'command_info.ui' applies.
#
# Created: Tue Jul  2 09:37:19 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FormCommandInfo(object):
    def setupUi(self, FormCommandInfo):
        FormCommandInfo.setObjectName("FormCommandInfo")
        FormCommandInfo.resize(1367, 741)
        FormCommandInfo.setAcceptDrops(False)
        self.stackedWidget = QtWidgets.QStackedWidget(FormCommandInfo)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1451, 751))
        self.stackedWidget.setObjectName("stackedWidget")
        self.All = QtWidgets.QWidget()
        self.All.setObjectName("All")
        self.tableWidgetCmd = QtWidgets.QTableWidget(self.All)
        self.tableWidgetCmd.setGeometry(QtCore.QRect(240, 0, 1131, 691))
        self.tableWidgetCmd.setObjectName("tableWidgetCmd")
        self.tableWidgetCmd.setColumnCount(11)
        self.tableWidgetCmd.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmd.setHorizontalHeaderItem(10, item)
        self.checkBoxBinary = QtWidgets.QCheckBox(self.All)
        self.checkBoxBinary.setGeometry(QtCore.QRect(640, 710, 70, 17))
        self.checkBoxBinary.setObjectName("checkBoxBinary")
        self.checkBoxDec = QtWidgets.QCheckBox(self.All)
        self.checkBoxDec.setGeometry(QtCore.QRect(560, 710, 71, 17))
        self.checkBoxDec.setObjectName("checkBoxDec")
        self.checkBoxHex = QtWidgets.QCheckBox(self.All)
        self.checkBoxHex.setGeometry(QtCore.QRect(470, 710, 81, 17))
        self.checkBoxHex.setChecked(True)
        self.checkBoxHex.setObjectName("checkBoxHex")
        self.checkBoxReserved = QtWidgets.QCheckBox(self.All)
        self.checkBoxReserved.setGeometry(QtCore.QRect(330, 710, 161, 17))
        self.checkBoxReserved.setChecked(True)
        self.checkBoxReserved.setObjectName("checkBoxReserved")
        self.pushButtonSave = QtWidgets.QPushButton(self.All)
        self.pushButtonSave.setGeometry(QtCore.QRect(1090, 700, 121, 41))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonGen = QtWidgets.QPushButton(self.All)
        self.pushButtonGen.setGeometry(QtCore.QRect(1230, 700, 121, 41))
        self.pushButtonGen.setObjectName("pushButtonGen")
        self.pushButtonSCL = QtWidgets.QPushButton(self.All)
        self.pushButtonSCL.setGeometry(QtCore.QRect(962, 700, 111, 41))
        self.pushButtonSCL.setObjectName("pushButtonSCL")
        self.treeWidgetCmd = QtWidgets.QTreeWidget(self.All)
        self.treeWidgetCmd.setGeometry(QtCore.QRect(0, 0, 241, 741))
        self.treeWidgetCmd.setWordWrap(False)
        self.treeWidgetCmd.setColumnCount(1)
        self.treeWidgetCmd.setObjectName("treeWidgetCmd")
        self.treeWidgetCmd.headerItem().setText(0, "1")
        self.treeWidgetCmd.header().setVisible(False)
        self.stackedWidget.addWidget(self.All)
        self.cmdlist = QtWidgets.QWidget()
        self.cmdlist.setMinimumSize(QtCore.QSize(1451, 0))
        self.cmdlist.setObjectName("cmdlist")
        self.tableWidgetCmdlist = QtWidgets.QTableWidget(self.cmdlist)
        self.tableWidgetCmdlist.setGeometry(QtCore.QRect(240, 0, 751, 691))
        self.tableWidgetCmdlist.setMaximumSize(QtCore.QSize(751, 691))
        self.tableWidgetCmdlist.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidgetCmdlist.setObjectName("tableWidgetCmdlist")
        self.tableWidgetCmdlist.setColumnCount(3)
        self.tableWidgetCmdlist.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmdlist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmdlist.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCmdlist.setHorizontalHeaderItem(2, item)
        self.pushButtonSU = QtWidgets.QPushButton(self.cmdlist)
        self.pushButtonSU.setGeometry(QtCore.QRect(290, 700, 151, 28))
        self.pushButtonSU.setObjectName("pushButtonSU")
        self.pushButtonSA = QtWidgets.QPushButton(self.cmdlist)
        self.pushButtonSA.setGeometry(QtCore.QRect(470, 700, 93, 28))
        self.pushButtonSA.setObjectName("pushButtonSA")
        self.treeWidgetCmdlist = QtWidgets.QTreeWidget(self.cmdlist)
        self.treeWidgetCmdlist.setGeometry(QtCore.QRect(0, 0, 241, 741))
        self.treeWidgetCmdlist.setWordWrap(False)
        self.treeWidgetCmdlist.setColumnCount(1)
        self.treeWidgetCmdlist.setObjectName("treeWidgetCmdlist")
        self.treeWidgetCmdlist.headerItem().setText(0, "1")
        self.treeWidgetCmdlist.header().setVisible(False)
        self.stackedWidget.addWidget(self.cmdlist)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setAcceptDrops(True)
        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)

        self.retranslateUi(FormCommandInfo)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormCommandInfo)

    def retranslateUi(self, FormCommandInfo):
        FormCommandInfo.setWindowTitle(QtWidgets.QApplication.translate("FormCommandInfo", "Form", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Command", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Dword", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Field", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Default", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Value", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Check", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Address", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Min", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(8).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Max", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(9).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Bitfield_low", None, -1))
        self.tableWidgetCmd.horizontalHeaderItem(10).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Bitfield_high", None, -1))
        self.checkBoxBinary.setText(QtWidgets.QApplication.translate("FormCommandInfo", "Binary", None, -1))
        self.checkBoxDec.setText(QtWidgets.QApplication.translate("FormCommandInfo", "Decimal", None, -1))
        self.checkBoxHex.setText(QtWidgets.QApplication.translate("FormCommandInfo", "Hexadecimal", None, -1))
        self.checkBoxReserved.setText(QtWidgets.QApplication.translate("FormCommandInfo", "Hide reserved field", None, -1))
        self.pushButtonSave.setText(QtWidgets.QApplication.translate("FormCommandInfo", "Save", None, -1))
        self.pushButtonGen.setText(QtWidgets.QApplication.translate("FormCommandInfo", "Generate", None, -1))
        self.pushButtonSCL.setText(QtWidgets.QApplication.translate("FormCommandInfo", "Show CMD List", None, -1))
        self.tableWidgetCmdlist.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Command", None, -1))
        self.tableWidgetCmdlist.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("FormCommandInfo", "HitCount", None, -1))
        self.tableWidgetCmdlist.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("FormCommandInfo", "Error", None, -1))
        self.pushButtonSU.setText(QtWidgets.QApplication.translate("FormCommandInfo", "Save Changes && Update", None, -1))
        self.pushButtonSA.setText(QtWidgets.QApplication.translate("FormCommandInfo", "Show All", None, -1))

