# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputwindow.ui',
# licensing of 'inputwindow.ui' applies.
#
# Created: Wed Jun 26 13:11:12 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_InputWindow(object):
    def setupUi(self, InputWindow):
        InputWindow.setObjectName("InputWindow")
        InputWindow.resize(549, 550)
        self.centralWidget = QtWidgets.QWidget(InputWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 501, 371))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setContentsMargins(5, 0, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.Height = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Height.setFont(font)
        self.Height.setObjectName("Height")
        self.gridLayout.addWidget(self.Height, 7, 0, 1, 1)
        self.RawTileType_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.RawTileType_input.setObjectName("RawTileType_input")
        self.gridLayout.addWidget(self.RawTileType_input, 1, 4, 1, 1)
        self.Width = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Width.setFont(font)
        self.Width.setObjectName("Width")
        self.gridLayout.addWidget(self.Width, 5, 0, 1, 1)
        self.GUID = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GUID.setFont(font)
        self.GUID.setObjectName("GUID")
        self.gridLayout.addWidget(self.GUID, 4, 0, 1, 1)
        self.ResTileType = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ResTileType.setFont(font)
        self.ResTileType.setObjectName("ResTileType")
        self.gridLayout.addWidget(self.ResTileType, 4, 3, 1, 1)
        self.EncFunc = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EncFunc.setFont(font)
        self.EncFunc.setObjectName("EncFunc")
        self.gridLayout.addWidget(self.EncFunc, 7, 3, 1, 1)
        self.Height_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Height_input.setObjectName("Height_input")
        self.gridLayout.addWidget(self.Height_input, 7, 2, 1, 1)
        self.EncFunc_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.EncFunc_input.setObjectName("EncFunc_input")
        self.gridLayout.addWidget(self.EncFunc_input, 7, 4, 1, 1)
        self.ResTileType_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ResTileType_input.setText("")
        self.ResTileType_input.setObjectName("ResTileType_input")
        self.gridLayout.addWidget(self.ResTileType_input, 4, 4, 1, 1)
        self.ResFormat_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ResFormat_input.setObjectName("ResFormat_input")
        self.gridLayout.addWidget(self.ResFormat_input, 5, 4, 1, 1)
        self.InputPath = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InputPath.setFont(font)
        self.InputPath.setObjectName("InputPath")
        self.gridLayout.addWidget(self.InputPath, 1, 0, 1, 1)
        self.RawFormat_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.RawFormat_input.setObjectName("RawFormat_input")
        self.gridLayout.addWidget(self.RawFormat_input, 3, 4, 1, 1)
        self.ResFormat = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ResFormat.setFont(font)
        self.ResFormat.setObjectName("ResFormat")
        self.gridLayout.addWidget(self.ResFormat, 5, 3, 1, 1)
        self.Component_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Component_input.setReadOnly(False)
        self.Component_input.setObjectName("Component_input")
        self.gridLayout.addWidget(self.Component_input, 3, 2, 1, 1)
        self.RawFormat = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RawFormat.setFont(font)
        self.RawFormat.setObjectName("RawFormat")
        self.gridLayout.addWidget(self.RawFormat, 3, 3, 1, 1)
        self.FrameNum_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.FrameNum_input.setObjectName("FrameNum_input")
        self.gridLayout.addWidget(self.FrameNum_input, 8, 4, 1, 1)
        self.RawTileType = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RawTileType.setFont(font)
        self.RawTileType.setObjectName("RawTileType")
        self.gridLayout.addWidget(self.RawTileType, 1, 3, 1, 1)
        self.GUID_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.GUID_input.setText("")
        self.GUID_input.setObjectName("GUID_input")
        self.gridLayout.addWidget(self.GUID_input, 4, 2, 1, 1)
        self.FrameNum = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FrameNum.setFont(font)
        self.FrameNum.setObjectName("FrameNum")
        self.gridLayout.addWidget(self.FrameNum, 8, 3, 1, 1)
        self.Component = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Component.setFont(font)
        self.Component.setObjectName("Component")
        self.gridLayout.addWidget(self.Component, 3, 0, 1, 1)
        self.InputPathText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.InputPathText.setReadOnly(False)
        self.InputPathText.setObjectName("InputPathText")
        self.gridLayout.addWidget(self.InputPathText, 1, 2, 1, 1)
        self.Width_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Width_input.setObjectName("Width_input")
        self.gridLayout.addWidget(self.Width_input, 5, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralWidget)
        self.buttonBox.setGeometry(QtCore.QRect(170, 460, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 371, 31))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        InputWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(InputWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 549, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuMain = QtWidgets.QMenu(self.menuBar)
        self.menuMain.setObjectName("menuMain")
        self.menuInput = QtWidgets.QMenu(self.menuBar)
        self.menuInput.setObjectName("menuInput")
        InputWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuMain.menuAction())
        self.menuBar.addAction(self.menuInput.menuAction())

        self.retranslateUi(InputWindow)
        QtCore.QMetaObject.connectSlotsByName(InputWindow)

    def retranslateUi(self, InputWindow):
        InputWindow.setWindowTitle(QtWidgets.QApplication.translate("InputWindow", "InputWindow", None, -1))
        self.Height.setText(QtWidgets.QApplication.translate("InputWindow", "Height", None, -1))
        self.Width.setText(QtWidgets.QApplication.translate("InputWindow", "Width", None, -1))
        self.GUID.setText(QtWidgets.QApplication.translate("InputWindow", "GUID", None, -1))
        self.ResTileType.setText(QtWidgets.QApplication.translate("InputWindow", "ResTileType", None, -1))
        self.EncFunc.setText(QtWidgets.QApplication.translate("InputWindow", "EncFunc", None, -1))
        self.InputPath.setText(QtWidgets.QApplication.translate("InputWindow", "Input Path", None, -1))
        self.ResFormat.setText(QtWidgets.QApplication.translate("InputWindow", "ResFormat", None, -1))
        self.RawFormat.setText(QtWidgets.QApplication.translate("InputWindow", "RawFormat", None, -1))
        self.RawTileType.setText(QtWidgets.QApplication.translate("InputWindow", "RawTileType", None, -1))
        self.FrameNum.setText(QtWidgets.QApplication.translate("InputWindow", "FrameNum", None, -1))
        self.Component.setText(QtWidgets.QApplication.translate("InputWindow", "Component", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("InputWindow", "Please type input parameters here.", None, -1))
        self.menuMain.setTitle(QtWidgets.QApplication.translate("InputWindow", "Main", None, -1))
        self.menuInput.setTitle(QtWidgets.QApplication.translate("InputWindow", "Input", None, -1))

