# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Tue Jun 11 13:28:23 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(805, 554)
        mainWindow.setBaseSize(QtCore.QSize(100, 100))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(30, 0, 30, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEditMediaPath = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMediaPath.sizePolicy().hasHeightForWidth())
        self.lineEditMediaPath.setSizePolicy(sizePolicy)
        self.lineEditMediaPath.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEditMediaPath.setObjectName("lineEditMediaPath")
        self.gridLayout.addWidget(self.lineEditMediaPath, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEditFrame = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFrame.sizePolicy().hasHeightForWidth())
        self.lineEditFrame.setSizePolicy(sizePolicy)
        self.lineEditFrame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEditFrame.setObjectName("lineEditFrame")
        self.gridLayout.addWidget(self.lineEditFrame, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditTestName = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTestName.sizePolicy().hasHeightForWidth())
        self.lineEditTestName.setSizePolicy(sizePolicy)
        self.lineEditTestName.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEditTestName.setObjectName("lineEditTestName")
        self.gridLayout.addWidget(self.lineEditTestName, 0, 1, 1, 1)
        self.comboBoxPlatform = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPlatform.sizePolicy().hasHeightForWidth())
        self.comboBoxPlatform.setSizePolicy(sizePolicy)
        self.comboBoxPlatform.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBoxPlatform.setObjectName("comboBoxPlatform")
        self.comboBoxPlatform.addItem("")
        self.comboBoxPlatform.addItem("")
        self.comboBoxPlatform.addItem("")
        self.comboBoxPlatform.addItem("")
        self.comboBoxPlatform.addItem("")
        self.comboBoxPlatform.addItem("")
        self.comboBoxPlatform.addItem("")
        self.comboBoxPlatform.addItem("")
        self.comboBoxPlatform.addItem("")
        self.comboBoxPlatform.addItem("")
        self.gridLayout.addWidget(self.comboBoxPlatform, 3, 1, 1, 1)
        self.comboBoxComponent = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxComponent.sizePolicy().hasHeightForWidth())
        self.comboBoxComponent.setSizePolicy(sizePolicy)
        self.comboBoxComponent.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBoxComponent.setObjectName("comboBoxComponent")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.gridLayout.addWidget(self.comboBoxComponent, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.lineEditRefFile = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRefFile.sizePolicy().hasHeightForWidth())
        self.lineEditRefFile.setSizePolicy(sizePolicy)
        self.lineEditRefFile.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEditRefFile.setObjectName("lineEditRefFile")
        self.gridLayout.addWidget(self.lineEditRefFile, 2, 1, 1, 1)
        self.pushButtonRef = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRef.sizePolicy().hasHeightForWidth())
        self.pushButtonRef.setSizePolicy(sizePolicy)
        self.pushButtonRef.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButtonRef.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButtonRef.setBaseSize(QtCore.QSize(200, 200))
        self.pushButtonRef.setObjectName("pushButtonRef")
        self.gridLayout.addWidget(self.pushButtonRef, 6, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.logBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logBrowser.sizePolicy().hasHeightForWidth())
        self.logBrowser.setSizePolicy(sizePolicy)
        self.logBrowser.setBaseSize(QtCore.QSize(60, 500))
        self.logBrowser.setObjectName("logBrowser")
        self.horizontalLayout.addWidget(self.logBrowser)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtWidgets.QApplication.translate("mainWindow", "Command Validator", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("mainWindow", "Input Cmd References File", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("mainWindow", "Platform", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("mainWindow", "Component", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("mainWindow", "Test Name", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("mainWindow", "Media Path", None, -1))
        self.comboBoxPlatform.setItemText(0, QtWidgets.QApplication.translate("mainWindow", "IGFX_TIGER_LAKE_LP", None, -1))
        self.comboBoxPlatform.setItemText(1, QtWidgets.QApplication.translate("mainWindow", "IGFX_SKYLAKE", None, -1))
        self.comboBoxPlatform.setItemText(2, QtWidgets.QApplication.translate("mainWindow", "IGFX_KABYLAKE", None, -1))
        self.comboBoxPlatform.setItemText(3, QtWidgets.QApplication.translate("mainWindow", "IGFX_BROXTON", None, -1))
        self.comboBoxPlatform.setItemText(4, QtWidgets.QApplication.translate("mainWindow", "IGFX_CHERRYVIEW", None, -1))
        self.comboBoxPlatform.setItemText(5, QtWidgets.QApplication.translate("mainWindow", "IGFX_BROADWELL", None, -1))
        self.comboBoxPlatform.setItemText(6, QtWidgets.QApplication.translate("mainWindow", "IGFX_VALLEYWELL", None, -1))
        self.comboBoxPlatform.setItemText(7, QtWidgets.QApplication.translate("mainWindow", "IGFX_HASWELL", None, -1))
        self.comboBoxPlatform.setItemText(8, QtWidgets.QApplication.translate("mainWindow", "IGFX_IVYBRIDGE", None, -1))
        self.comboBoxPlatform.setItemText(9, QtWidgets.QApplication.translate("mainWindow", "IGFX_GT", None, -1))
        self.comboBoxComponent.setItemText(0, QtWidgets.QApplication.translate("mainWindow", "Decode", None, -1))
        self.comboBoxComponent.setItemText(1, QtWidgets.QApplication.translate("mainWindow", "Encode", None, -1))
        self.comboBoxComponent.setItemText(2, QtWidgets.QApplication.translate("mainWindow", "VP", None, -1))
        self.comboBoxComponent.setItemText(3, QtWidgets.QApplication.translate("mainWindow", "CP", None, -1))
        self.comboBoxComponent.setItemText(4, QtWidgets.QApplication.translate("mainWindow", "CM", None, -1))
        self.comboBoxComponent.setItemText(5, QtWidgets.QApplication.translate("mainWindow", "Kernel", None, -1))
        self.comboBoxComponent.setItemText(6, QtWidgets.QApplication.translate("mainWindow", "Upstream", None, -1))
        self.comboBoxComponent.setItemText(7, QtWidgets.QApplication.translate("mainWindow", "MSDK", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("mainWindow", "Frame", None, -1))
        self.lineEditRefFile.setText(QtWidgets.QApplication.translate("mainWindow", "test.xml", None, -1))
        self.pushButtonRef.setText(QtWidgets.QApplication.translate("mainWindow", "Read File", None, -1))

