# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Fri May 24 10:02:19 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 587)
        MainWindow.setBaseSize(QtCore.QSize(100, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 80, 921, 441))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(5, 0, 50, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditRefFile_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditRefFile_2.setObjectName("lineEditRefFile_2")
        self.gridLayout.addWidget(self.lineEditRefFile_2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.pushButtonBspec = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBspec.sizePolicy().hasHeightForWidth())
        self.pushButtonBspec.setSizePolicy(sizePolicy)
        self.pushButtonBspec.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButtonBspec.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButtonBspec.setBaseSize(QtCore.QSize(200, 200))
        self.pushButtonBspec.setObjectName("pushButtonBspec")
        self.gridLayout.addWidget(self.pushButtonBspec, 7, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEditDataFile = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditDataFile.setObjectName("lineEditDataFile")
        self.gridLayout.addWidget(self.lineEditDataFile, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.lineEditURL = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditURL.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEditURL.setObjectName("lineEditURL")
        self.gridLayout.addWidget(self.lineEditURL, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.comboBoxComponent = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBoxComponent.setObjectName("comboBoxComponent")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.comboBoxComponent.addItem("")
        self.gridLayout.addWidget(self.comboBoxComponent, 6, 1, 1, 1)
        self.lineEditOut = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditOut.setObjectName("lineEditOut")
        self.gridLayout.addWidget(self.lineEditOut, 8, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 4, 1, 1, 1)
        self.pushButtonGen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonGen.sizePolicy().hasHeightForWidth())
        self.pushButtonGen.setSizePolicy(sizePolicy)
        self.pushButtonGen.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButtonGen.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButtonGen.setBaseSize(QtCore.QSize(15, 15))
        self.pushButtonGen.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonGen.setObjectName("pushButtonGen")
        self.gridLayout.addWidget(self.pushButtonGen, 8, 2, 1, 1)
        self.pushButtonRef = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRef.sizePolicy().hasHeightForWidth())
        self.pushButtonRef.setSizePolicy(sizePolicy)
        self.pushButtonRef.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButtonRef.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButtonRef.setBaseSize(QtCore.QSize(200, 200))
        self.pushButtonRef.setObjectName("pushButtonRef")
        self.gridLayout.addWidget(self.pushButtonRef, 3, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.logBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logBrowser.sizePolicy().hasHeightForWidth())
        self.logBrowser.setSizePolicy(sizePolicy)
        self.logBrowser.setBaseSize(QtCore.QSize(60, 500))
        self.logBrowser.setObjectName("logBrowser")
        self.horizontalLayout.addWidget(self.logBrowser)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lineEditRefFile_2.setText(QtWidgets.QApplication.translate("MainWindow", "test.xml", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Input Cmd References File", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Platform", None, -1))
        self.pushButtonBspec.setText(QtWidgets.QApplication.translate("MainWindow", "Get Info From Bspec", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Input Data File", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Component", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "URL", None, -1))
        self.lineEditURL.setText(QtWidgets.QApplication.translate("MainWindow", "https://gfxspecs.intel.com/Predator/Home/Index/18576", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Output Direcory", None, -1))
        self.comboBoxComponent.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Decode", None, -1))
        self.comboBoxComponent.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Encode", None, -1))
        self.comboBoxComponent.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "VP", None, -1))
        self.comboBoxComponent.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "CP", None, -1))
        self.comboBoxComponent.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "CM", None, -1))
        self.comboBoxComponent.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Kernel", None, -1))
        self.comboBoxComponent.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "Upstream", None, -1))
        self.comboBoxComponent.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "MSDK", None, -1))
        self.lineEditOut.setText(QtWidgets.QApplication.translate("MainWindow", "output.xml", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Gen8", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Gen9", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Gen10", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Gen11", None, -1))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "Gen12", None, -1))
        self.pushButtonGen.setText(QtWidgets.QApplication.translate("MainWindow", "Generate XML", None, -1))
        self.pushButtonRef.setText(QtWidgets.QApplication.translate("MainWindow", "Get Info From Vecs", None, -1))

